Fix for error C2338: GRequiresCookedDataPlatformMask must be large enough to support all shader platforms (introduced in cl 6939155)
#rb none

[CL 6942780 by PJ Kack in Dev-Core branch]