SwitchboardListener: Fix for building with bForceEnableExceptions (error C2712: cannot use __try in functions that require object unwinding).
#jira UE-145172
#rb matt.johnson
#preflight 6244bb9ff4217035fa806ae9

[CL 19564149 by zach brockway in ue5-main branch]