Cherry-picking:
14113806 Adding CustomAttribute feature to support float/int/string curve data within AnimationSequences on a per-bone basis
#rb Thomas.Sarkanen
[FYI] Alejandro.Arango, Benoit.Deschenes, Max.Chen, Thomas.Kilkenny

"14143597 Add customization details for (Baked)Custom attribute structures
- Showing bone name rather than the index
- Grouping the attributes according to their types
- Only show number of keys for individual attributes (no data)
#rb Thomas.Sarkanen"

14143610 Add support for URO/interpolation of custom attributes
#misc fix attribute look-up crash with nullptr skeletal mesh
#rb Thomas.Sarkanen

14198402 Hide baked custom attributes property, causing performance issue with Slate

14201044 //UE4/Dev-VirtualProduction - NonUnity Compile UE4Editor Win64 - \Private\CustomAttributeCustomization.cpp(48): error C2027: use of undefined type 'UAnimSequence'
#fix add AnimSequence.h include
#jira UE-97700
#rb trivial

14201364 //Ue4/Dev-VirtualProduction - UE4Game XboxOne - AnimSequence.h(439): warning C4996: 'UAnimSequenceBase::GetAnimationPose': Use other GetAnimationPose signature Please update your code to the new API before upgrading to the next release
#jira UE-97684
#fix moved deprecated functionality to AnimSequenceBase and delete all overrides from child classes
#rb trivial

14207790 //UE4/Dev-VirtualProduction - UE4Game Switch - TMemStackAllocator<0u> >* TBaseCustomAttributes<FCompactPoseBoneIndex, TMemStackAllocator<0u> >::GetValuesArray_Internal<float>()
#fix moved away from templated get-ters for value arrays, replaced with regular function overloading
#jira UE-97677
#rb trivial

14143554 + Fix baked additive data for Custom Attributes. Previously the base sequence data was not taken into account.
+ Changing additive automation test to use an animation sequence as base pose rather than ref-pose
#rb Thomas.Sarkanen


#ROBOMERGE-OWNER: jurre.debaare
#ROBOMERGE-AUTHOR: jurre.debaare
#ROBOMERGE-SOURCE: CL 14297806 in //UE4/Release-4.26/...
#ROBOMERGE-BOT: RELEASE (Release-4.26 -> Release-Engine-Staging) (v732-14297381)

[CL 14297849 by jurre debaare in Release-Engine-Staging branch]