Lens Calibration. [Fix] Non unity build Using the raw pointer instead of static initialization of Abstract static class
error: variable type 'FBaseLensTable' is an abstract class,
https://horde.devtools.epicgames.com/job/60d22afc78c3b000011b8c2b?step=9969&issue=81489


#rb Simon Therriault
#jira none
#lockdown simon.tourangeau

[CL 16755907 by Denys Dubinin in 4.27 branch]