CIS - Validate Compiler Toolchains, fixed error C2039: 'Softs': is not a member of 'UE::Chaos', due to the compiler getting confused by the using namespace Softs in the statement while compiling an unrelated UE_CLOG macro.
#rb trivial
#preflight 634fdaf9c9559712ede70019
#jira none
#rnx

[CL 22622345 by kriss gossart in ue5-main branch]