Fix for [25.10 Thread] CIS Editor Error - InstancedStructDetails.cpp(449): error C2660: 'UE::StructUtils::Private::GetCommonScriptStruct': function does not take 1 argument
Updating engine change for 25.10 Original Change

Show ToolTip text for instance structs instead of DisplayName text.


[REVIEW] [at]daren.cheng

#rb daren.cheng

[CL 25422254 by vlad golovan in ue5-main branch]