[WaveformEditor] Fix for  error C2036 in non unity builds caused by transformation settings #preflight 632a0117f87253e021223f6d #trivial #rb none
[CL 22100930 by igor dallavanzi in ue5-main branch]