AsyncLoading2: Move GC-related importstore logic from GT callback to ALT resume phase. Make import store more reliable by not relying on Object->HasAnyFlags(RF_WasLoaded | RF_Public) filtering (We can take the hit of checking all unreachable objects on the ALT) The logic can be forced to run on the GT again with s.RemoveUnreachableObjectsOnGT=1, which in debug and development builds enables extra verifications.
Return actual number of destroyed objects from FAsyncPurge::GetObjectsDestroyedSinceLastMarkPhase to make these logs correct:
LogGarbage: 2.118 ms for incrementally purging unreachable objects (FinishDestroyed: 16176, Destroyed: 1571 / 16176)
LogGarbage: 2.303 ms for incrementally purging unreachable objects (FinishDestroyed: 16176, Destroyed: 1971 / 16176)

#jira UE-159941
#rb carlmagnus.nordin
#rnx
#preflight 62f4f8a7ad3bd8ad64107073

AsyncLoading2: Make sure to call RemoveUnreachableObjects also when running without the Async Loading Thread (follow up fix for 21353595).
Increase log verbosity back to Display for RemoveUnreachableObjects.
Remove unnecessary FGCScopeGuard from the TickAsyncThreadFromGameThread.

#jira UE-160904
#rb carlmagnus.nordin
#rnx
#preflight 62f9fb9de67510be05328c1f

AsyncLoading2: Improve the initial load logic from cl 20643384.
Replace FinalizeInitialLoad with CompleteRegistrationEvent and use the same code path with/without the async loading thread.
Strip the FindAllScriptObjects logic from test and shipping builds.
Optimize initial load NotifyRegistrationEvent handling by passing the finished object instead of looking it up by name.

#rb carlmagnus.nordin
#rnx
#preflight 62fb3e5b4b04bcb92d500a68

AsyncLoading2: Only start the thread when it should be enabled (bug fix for 21402146)

#rb carlmagnus.nordin
#rnx
#preflight 62fb4b35cf7afa018b857b6e

AsyncLoading2: Prevent double removal of leaked and renamed packages (fix for 21060094 and 21417438).

The double removal would occur in the following scenario...
1. LoadPackageAsync(PackageA)
2. GC & VerifyLoadMapWorldCleanup where PackageA is leaking
3. OnLeakedPackageRename(PackageA)
4. LoadPackageAsync(PackageA)
5. GC & VerifyLoadMapWorldCleanup where old PackageA is destroyed (and new PackageA is destroyed or leaking)

In development step 5 would cause the following assert in FLoadedPackageRef::FPublicExportMap::VerifyAllObjectsRemoved:
Error: Assertion failed: ObjectIndex < 0

In test/shipping step 5 would cause an FLoadedPackageRef assert or nullptr crash in
FGlobalImportStore::RemovePublicExports called from VerifyLoadMapWorldCleanup/OnLeakedPackageRename or CollectGarbageInternal/NotifyUnreachableObjects.

Tested BR replay and StW on PC.

#jira UE-159809, FORT-504960, FORT-494296, FORT-497087
#rb carlmagnus.nordin
[FYI] robert.millar
#rnx

AsyncLoading2: Fix potential race between OnLeakedPackageRename on GT and RemoveUnreachableObjects on ALT (relates to 21353595 and 21426054)

#rb carlmagnus.nordin
#rnx
#preflight 62ff3384200ff87e07e6b97c

AsyncLoading2: natvis compatiblity fixes for latest source code

#rb trivial
#rnx


#ushell-cherrypick of 21377403 by pj.kack
#ushell-cherrypick of 21384529 by pj.kack
#ushell-cherrypick of 21402163 by pj.kack
#ushell-cherrypick of 21402271 by pj.kack
#ushell-cherrypick of 21425777 by pj.kack
#ushell-cherrypick of 21454977 by pj.kack
#ushell-cherrypick of 21455802 by pj.kack

[CL 21697327 by pj kack in ue5-main branch]